coverage:
  precision: 2
  round: down
  range: 0..100
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 95%
        threshold: 1%
        if_not_found: success
ignore:
  - "test/**/*"
  - "lib/**/*"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true