name: Foundry CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    name: Unit & local integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Run local tests (no fork)
        run: forge test --gas-report

  fork:
    name: Mainnet-fork tests
    needs: unit
    runs-on: ubuntu-latest
    # Only run this job when the secret is configured
    if: ${{ secrets.MAINNET_RPC_URL != '' }}

    env:
      # Expose the RPC to the test suite (your tests call vm.envString("MAINNET_RPC_URL"))
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      # Optional: make sure we don't accidentally pick up a repo .env that could shadow the secret
      - name: Remove repo .env if present (avoid conflicts)
        run: rm -f .env

      - name: Run forked tests (Uniswap V2, etc.)
        run: |
          forge test \
            --match-path "test/Fork_*.t.sol" \
            --gas-report
