name: Foundry CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    name: Unit & local integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Run local tests (no fork)
        run: forge test --gas-report

  fork:
    name: Mainnet-fork tests
    needs: unit
    runs-on: ubuntu-latest
    env:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      # Write a clean .env for Foundry to read
      - name: Write .env for tests
        run: |
          echo "::add-mask::${MAINNET_RPC_URL}"
          printf "MAINNET_RPC_URL=%s\n" "${MAINNET_RPC_URL}" > .env

      - name: Run forked tests (Uniswap V2, etc.)
        run: forge test --match-path "test/Fork_*.t.sol" --gas-report
